# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
Binomial_American_Greeks_cpp <- function(initial_price = 100, exercise_price = 100, r = 0, time_to_maturity = 1, volatility = 0.3, dividend_yield = 0, payoff = "call", steps = 20L) {
    .Call(`_greeks_Binomial_American_Greeks_cpp`, initial_price, exercise_price, r, time_to_maturity, volatility, dividend_yield, payoff, steps)
}

#' @export
calc_I_1 <- function(X, steps, dt) {
    .Call(`_greeks_calc_I_1`, X, steps, dt)
}

#' @export
calc_I_2 <- function(X, steps, dt) {
    .Call(`_greeks_calc_I_2`, X, steps, dt)
}

#' @export
calc_I_3 <- function(X, steps, dt) {
    .Call(`_greeks_calc_I_3`, X, steps, dt)
}

#' @export
calc_X <- function(W, steps, paths, dt, initial_price, volatility, r) {
    .Call(`_greeks_calc_X`, W, steps, paths, dt, initial_price, volatility, r)
}

#' @export
calc_tXW <- function(X, W, steps, paths, dt) {
    .Call(`_greeks_calc_tXW`, X, W, steps, paths, dt)
}

