on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: codecov

jobs:
  codecov:
    runs-on: ${{ matrix.config.os }}

steps:
- uses: actions/checkout@main
- uses: codecov/codecov-action@v1
